title:             inders.in
center_title:      INDERS.IN
email:             indermohansinghk7@gmail.com
description:       CODE | MUSIC
author:            Indermohan Singh
baseurl:           ""
url:               "https://inders.in"
excerpt_separator: '<!-- more -->'
encoding: utf-8

# Social Profiles
twitter_username:  imsinghk7
github_username:   imsingh
facebook_username:

#disqus
disqus:
  shortname: indersin

# Build settings
markdown: kramdown
highlighter: rouge
destination: ./docs/
permalink: pretty

paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate


